spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fb_clone
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      minimumIdle: 5
      maximumPoolSize: 30
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect






